modLoader="javafml"
loaderVersion="[46,)"
license="LGPLv.3"
issueTrackerURL="https://github.com/GoryMoon/PlayerMobs/issues"

[[mods]]
    modId="player_mobs"
    version="${file.jarVersion}"
    displayName="Player Mobs"
    updateJSONURL="https://raw.githubusercontent.com/GoryMoon/PlayerMobs/update/versions.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/player-mobs"
    logoFile="banner.png"
    itemIcon="minecraft:player_head"
    credits="Thanks to Headcrumbs for the base idea."
    authors="GoryMoon"
    description='''
Adds a mob that has other players skin.'''

[[dependencies.player_mobs]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.player_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
