name: Mod CD

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
        run: ./.github/prepare_keystore.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_keyStore: ./release.keystore
          ORG_GRADLE_PROJECT_keyStoreAlias: ${{ secrets.KEYSTORE_ALIAS }}
          ORG_GRADLE_PROJECT_keyStorePass: ${{ secrets.KEYSTORE_PASS }}
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/libs
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./libs
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: "./libs/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          draft: false
          prerelease: false