name: Mod Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./libs

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./libs/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          draft: false
          prerelease: false